import { expect, test, type Page } from '@playwright/test'

async function signInForTest(page: Page) {
  await page.addInitScript(() => {
    localStorage.setItem('mybook-auth', JSON.stringify({ state: { isAuthenticated: true, email: 'tester@example.com', accessToken: 'test-token', accessTokenExpiresAt: Date.now() + 3_600_000 }, version: 0 }))
  })
  await page.route('https://www.googleapis.com/**', async (route) => {
    const request = route.request()
    if (request.method() === 'GET') await route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({ files: [] }) })
    else await route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({ id: `drive-${Date.now()}`, name: 'MyBook', webViewLink: 'https://drive.google.com/test' }) })
  })
  await page.goto('/home')
}

test('a returning signed-in user goes directly to home', async ({ page }) => {
  await signInForTest(page)
  await page.reload()

  await expect(page).toHaveURL(/\/home$/)
  await expect(page.getByText(/Recent files/i)).toBeVisible()
})

test('login page provides Google sign-in without calling Drive', async ({ page }) => {
  await page.goto('/login')
  await expect(page.getByRole('heading', { name: 'Welcome to MyBook' })).toBeVisible()
  await expect(page.getByRole('button', { name: /continue with google/i })).toBeVisible()
})

test('document create, local save, backup, home open, rename, and delete', async ({ page }) => {
  await signInForTest(page)
  await page.getByRole('button', { name: 'Create new' }).click()
  await page.getByRole('menuitem', { name: 'New document' }).click()
  const editor = page.getByRole('textbox', { name: 'Document content' })
  await expect(editor).toBeVisible()
  await editor.fill('Meeting notes saved locally')
  await expect(page.getByText('Saved locally')).toBeVisible({ timeout: 5_000 })
  await page.getByRole('button', { name: 'Back up now' }).click()
  await expect(page.getByText(/Google Drive backup complete|backup created|backup updated/i)).toBeVisible({ timeout: 10_000 })
  await page.getByRole('button', { name: 'Close document' }).click()
  await expect(page.getByRole('button', { name: /Untitled document/i })).toBeVisible()
  await page.getByRole('button', { name: /More actions for Untitled document/i }).click()
  await page.getByRole('menuitem', { name: 'Rename' }).click()
  await page.getByLabel('File name').fill('Meeting Notes')
  await page.getByRole('button', { name: 'Save' }).click()
  await page.getByRole('button', { name: /More actions for Meeting Notes/i }).click()
  await page.getByRole('menuitem', { name: 'Move to Trash' }).click()
  await expect(page.getByRole('tab', { name: 'Recent' })).toBeVisible()
})

test('spreadsheet can be created and backed up with mocked Drive', async ({ page }) => {
  await signInForTest(page)
  await page.getByRole('button', { name: 'Create new' }).click()
  await page.getByRole('menuitem', { name: 'New spreadsheet' }).click()
  await expect(page.getByRole('region', { name: /Spreadsheet editor/i })).toBeVisible({ timeout: 15_000 })
  await page.getByRole('button', { name: 'Back up now' }).click()
  await expect(page.getByText(/Google Drive backup complete|backup created|backup updated/i)).toBeVisible({ timeout: 15_000 })
})

test('document table controls support resizing and fixed visible rows', async ({ page }) => {
  await signInForTest(page)
  await page.getByRole('button', { name: 'Create new' }).click()
  await page.getByRole('menuitem', { name: 'New document' }).click()

  const editor = page.getByRole('textbox', { name: 'Document content' })
  await expect(editor).toBeVisible()
  await editor.click()
  await page.keyboard.type('/table')
  await page.getByRole('option', { name: 'Basic Table' }).click()

  const table = page.locator('.tiptap table')
  await expect(table).toBeVisible()
  await table.hover()
  await expect(page.getByLabel('Block controls')).toHaveCount(1)
  await expect(page.getByRole('button', { name: 'Add block' })).toHaveCount(1)
  await expect(page.locator('.mybook-table-row-grip')).toHaveCount(2)
  const firstCell = table.locator('td').first()
  const firstCellBox = await firstCell.boundingBox()
  if (!firstCellBox) throw new Error('The first table cell has no layout box')
  await page.mouse.move(firstCellBox.x + firstCellBox.width - 2, firstCellBox.y + firstCellBox.height / 2)
  await expect(page.locator('.column-resize-handle')).toHaveCount(2)

  await page.getByRole('button', { name: 'Row 1 actions' }).evaluate((button) => (button as HTMLButtonElement).click())
  await page.getByRole('menuitemcheckbox', { name: 'Fixed visible rows' }).click()
  const tableWrapper = table.locator('xpath=..')
  await expect(tableWrapper).toHaveClass(/tableWrapper/)
  await expect(tableWrapper).toHaveAttribute('data-fixed-rows', 'true')
  const visibleRowCount = page.getByRole('spinbutton', { name: 'Visible row count' })
  await expect(visibleRowCount).toHaveValue('5')
  await visibleRowCount.fill('3')
  await expect(visibleRowCount).toHaveValue('3')
  await expect(tableWrapper).toHaveAttribute('data-fixed-row-count', '3')
})

test('document table row and column menus apply background color and alignment', async ({ page }) => {
  await signInForTest(page)
  await page.getByRole('button', { name: 'Create new' }).click()
  await page.getByRole('menuitem', { name: 'New document' }).click()
  const editor = page.getByRole('textbox', { name: 'Document content' })
  await editor.click()
  await page.getByRole('button', { name: 'Basic Table' }).click()
  const table = page.locator('.tiptap table')
  await expect(table).toBeVisible()

  await page.getByRole('button', { name: 'Row 1 actions' }).click()
  await page.getByRole('menuitem', { name: 'Color' }).click()
  await page.getByRole('menuitemradio', { name: 'Blue' }).click()
  await expect(table.locator('td').nth(0)).toHaveCSS('background-color', 'rgb(219, 234, 254)')
  await expect(table.locator('td').nth(1)).toHaveCSS('background-color', 'rgb(219, 234, 254)')

  await page.getByRole('button', { name: 'Column 2 actions' }).evaluate((button) => (button as HTMLButtonElement).click())
  await page.getByRole('menuitem', { name: 'Align' }).click()
  await page.getByRole('menuitemradio', { name: 'center' }).click()
  await expect(table.locator('td').nth(1)).toHaveCSS('text-align', 'center')
})

test('document table header colors support mixed cell colors and whole-row colors', async ({ page }) => {
  await signInForTest(page)
  await page.getByRole('button', { name: 'Create new' }).click()
  await page.getByRole('menuitem', { name: 'New document' }).click()
  const editor = page.getByRole('textbox', { name: 'Document content' })
  await editor.click()
  await page.getByRole('button', { name: 'Basic Table' }).click()
  const table = page.locator('.tiptap table')
  await expect(table).toBeVisible()

  await page.getByRole('button', { name: 'Row 1 actions' }).click()
  await page.getByRole('menuitemcheckbox', { name: 'Header row' }).click()
  await expect(table.locator('th')).toHaveCount(2)

  await page.getByRole('button', { name: 'Column 1 actions' }).evaluate((button) => (button as HTMLButtonElement).click())
  await page.getByRole('menuitem', { name: 'Color' }).click()
  await page.getByRole('menuitemradio', { name: 'Blue' }).click()
  await expect(table.locator('th').nth(0)).toHaveCSS('background-color', 'rgb(219, 234, 254)')
  await expect(table.locator('th').nth(1)).not.toHaveCSS('background-color', 'rgb(219, 234, 254)')

  await page.getByRole('button', { name: 'Row 1 actions' }).evaluate((button) => (button as HTMLButtonElement).click())
  await page.getByRole('menuitem', { name: 'Color' }).click()
  await page.getByRole('menuitemradio', { name: 'Green' }).click()
  await expect(table.locator('th').nth(0)).toHaveCSS('background-color', 'rgb(220, 252, 231)')
  await expect(table.locator('th').nth(1)).toHaveCSS('background-color', 'rgb(220, 252, 231)')
})

test('table row and column selection stays scoped to the active table', async ({ page }) => {
  await signInForTest(page)
  await page.getByRole('button', { name: 'Create new' }).click()
  await page.getByRole('menuitem', { name: 'New document' }).click()
  const editor = page.getByRole('textbox', { name: 'Document content' })
  await editor.click()
  await page.getByRole('button', { name: 'Basic Table' }).click()
  await page.keyboard.press('End')
  await page.keyboard.press('Enter')
  await page.getByRole('button', { name: 'Basic Table' }).click()
  const tables = page.locator('.tiptap table')
  await expect(tables).toHaveCount(2)

  await tables.nth(1).locator('td').first().click()
  await tables.nth(1).hover()
  await page.getByRole('button', { name: 'Column 2 actions' }).last().evaluate((button) => (button as HTMLButtonElement).click())
  await expect(page.locator('.mybook-table-selected-column')).toHaveCount(2)
  await expect.poll(() => page.locator('.mybook-table-selected-column').evaluateAll((cells) => cells.every((cell) => Array.from(document.querySelectorAll('.tiptap table')).indexOf(cell.closest('table')!) === 1))).toBe(true)
})

test('clicking below a trailing table creates the next block', async ({ page }) => {
  await signInForTest(page)
  await page.getByRole('button', { name: 'Create new' }).click()
  await page.getByRole('menuitem', { name: 'New document' }).click()

  const editor = page.getByRole('textbox', { name: 'Document content' })
  await editor.click()
  await page.getByRole('button', { name: 'Basic Table' }).click()
  const table = page.locator('.tiptap table')
  await expect(table).toBeVisible()
  const tableBox = await table.boundingBox()
  if (!tableBox) throw new Error('Trailing table has no layout box')
  await page.mouse.click(tableBox.x + 20, tableBox.y + tableBox.height + 56)
  await expect(editor.locator('p').last()).toHaveClass(/mybook-empty-block-placeholder/)
  await table.hover()
  const addRow = page.getByRole('button', { name: 'Add row', exact: true })
  const addRowBox = await addRow.boundingBox()
  const paragraphBox = await editor.locator('p').last().boundingBox()
  if (!addRowBox || !paragraphBox) throw new Error('Trailing table controls or paragraph has no layout box')
  expect(addRowBox.y + addRowBox.height).toBeLessThanOrEqual(paragraphBox.y)
  await page.keyboard.type('Next block')
  await expect(editor.locator('p').last()).toHaveText('Next block')
})

test('document table columns resize from dividers including the last column', async ({ page }) => {
  await signInForTest(page)
  await page.getByRole('button', { name: 'Create new' }).click()
  await page.getByRole('menuitem', { name: 'New document' }).click()

  const editor = page.getByRole('textbox', { name: 'Document content' })
  await editor.click()
  await page.getByRole('button', { name: 'Basic Table' }).click()
  const table = page.locator('.tiptap table')
  await expect(table).toBeVisible()
  const firstCell = table.locator('td').first()
  const firstCellBefore = await firstCell.boundingBox()
  if (!firstCellBefore) throw new Error('First column has no layout box')
  await page.mouse.move(firstCellBefore.x + firstCellBefore.width - 2, firstCellBefore.y + firstCellBefore.height / 2)
  const handles = page.locator('.column-resize-handle')
  await expect(handles).toHaveCount(2)
  const firstHandle = handles.nth(0)
  const firstHandleBox = await firstHandle.boundingBox()
  if (!firstHandleBox) throw new Error('First column resize handle has no layout box')
  await page.mouse.move(firstHandleBox.x + firstHandleBox.width / 2, firstHandleBox.y + firstHandleBox.height / 2)
  await page.mouse.down()
  await page.mouse.move(firstHandleBox.x + 36, firstHandleBox.y + firstHandleBox.height / 2, { steps: 5 })
  await page.mouse.up()
  const firstCellAfter = await firstCell.boundingBox()
  if (!firstCellAfter) throw new Error('First column has no layout box after resize')
  expect(firstCellAfter.width).toBeGreaterThan(firstCellBefore.width + 20)

  const lastHandle = handles.nth(1)
  const lastHandleBox = await lastHandle.boundingBox()
  const lastCellBefore = await table.locator('td').nth(1).boundingBox()
  if (!lastHandleBox || !lastCellBefore) throw new Error('Last column resize handle has no layout box')
  await page.mouse.move(lastHandleBox.x + lastHandleBox.width / 2, lastHandleBox.y + lastHandleBox.height / 2)
  await page.mouse.down()
  await page.mouse.move(lastHandleBox.x - 24, lastHandleBox.y + lastHandleBox.height / 2, { steps: 5 })
  await page.mouse.up()
  const lastCellAfter = await table.locator('td').nth(1).boundingBox()
  if (!lastCellAfter) throw new Error('Last column has no layout box after resize')
  expect(lastCellAfter.width).toBeGreaterThan(lastCellBefore.width + 12)
})

test('document view mode persists after refresh', async ({ page }) => {
  await signInForTest(page)
  await page.getByRole('button', { name: 'Create new' }).click()
  await page.getByRole('menuitem', { name: 'New document' }).click()
  await page.getByRole('button', { name: 'Full' }).click()
  await expect(page.getByRole('button', { name: 'Full' })).toHaveAttribute('aria-pressed', 'true')
  await page.reload()
  await expect(page.getByRole('button', { name: 'Full' })).toHaveAttribute('aria-pressed', 'true')
})

test('document scrolls when the pointer is over the empty page margin', async ({ page }) => {
  await signInForTest(page)
  await page.getByRole('button', { name: 'Create new' }).click()
  await page.getByRole('menuitem', { name: 'New document' }).click()
  const editor = page.getByRole('textbox', { name: 'Document content' })
  await editor.fill(Array.from({ length: 40 }, (_, index) => `Line ${index + 1}`).join('\n'))
  await expect(editor).toBeVisible()
  const canvas = page.locator('.mybook-document-canvas')
  const canvasBox = await canvas.boundingBox()
  if (!canvasBox) throw new Error('Document canvas has no layout box')
  await page.mouse.move(canvasBox.x + 8, canvasBox.y + canvasBox.height / 2)
  const before = await page.locator('main').evaluate((main) => main.scrollTop)
  await page.mouse.wheel(0, 700)
  await expect.poll(() => page.locator('main').evaluate((main) => main.scrollTop)).toBeGreaterThan(before)
})

test('fixed visible rows shows the configured rows without clipping', async ({ page }) => {
  await signInForTest(page)
  await page.getByRole('button', { name: 'Create new' }).click()
  await page.getByRole('menuitem', { name: 'New document' }).click()

  const editor = page.getByRole('textbox', { name: 'Document content' })
  await editor.click()
  await page.getByRole('button', { name: 'Basic Table' }).click()
  const table = page.locator('.tiptap table')
  await expect(table).toBeVisible()
  await table.hover()
  const addRow = page.getByRole('button', { name: 'Add row', exact: true })
  for (let index = 0; index < 4; index += 1) await addRow.click({ force: true })
  await expect(table.locator('tr')).toHaveCount(6)
  await table.scrollIntoViewIfNeeded()
  await page.waitForTimeout(100)

  await page.getByRole('button', { name: 'Row 1 actions' }).evaluate((button) => (button as HTMLButtonElement).click())
  await page.getByRole('menuitemcheckbox', { name: 'Fixed visible rows' }).click()
  const tableWrapper = table.locator('xpath=..')
  const viewport = await tableWrapper.evaluate((wrapper) => {
    const rows = Array.from(wrapper.querySelectorAll('tr'))
    const fifthRow = rows[4]?.getBoundingClientRect()
    const wrapperRect = wrapper.getBoundingClientRect()
    return {
      fifthBottom: fifthRow?.bottom ?? 0,
      wrapperBottom: wrapperRect.bottom,
      clientHeight: wrapper.clientHeight,
      scrollHeight: wrapper.scrollHeight,
      style: wrapper.getAttribute('style'),
    }
  })
  expect(viewport.fifthBottom).toBeLessThanOrEqual(viewport.wrapperBottom + 1)
  expect(viewport.scrollHeight).toBeGreaterThan(viewport.clientHeight)
})

test('document table menu closes with Escape', async ({ page }) => {
  await signInForTest(page)
  await page.getByRole('button', { name: 'Create new' }).click()
  await page.getByRole('menuitem', { name: 'New document' }).click()

  const editor = page.getByRole('textbox', { name: 'Document content' })
  await editor.click()
  await page.keyboard.type('/table')
  await page.getByRole('option', { name: 'Basic Table' }).click()
  const table = page.locator('.tiptap table')
  await expect(table).toBeVisible()

  await page.getByRole('button', { name: 'Row 1 actions' }).click()
  await expect(page.locator('.mybook-table-manual-menu')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.locator('.mybook-table-manual-menu')).toBeHidden()
})

test('document table row menu toggles the header row', async ({ page }) => {
  await signInForTest(page)
  await page.getByRole('button', { name: 'Create new' }).click()
  await page.getByRole('menuitem', { name: 'New document' }).click()

  const editor = page.getByRole('textbox', { name: 'Document content' })
  await editor.click()
  await page.keyboard.type('/table')
  await page.getByRole('option', { name: 'Basic Table' }).click()
  const table = page.locator('.tiptap table')
  await expect(table).toBeVisible()
  await page.getByRole('button', { name: 'Row 1 actions' }).click()
  await page.getByRole('menuitemcheckbox', { name: 'Header row' }).click()
  await expect(table.locator('th')).toHaveCount(2)
  await expect(table.locator('th').first()).not.toHaveCSS('background-color', 'color(srgb 0.576471 0.772549 0.992157 / 0.18)')
})

test('document table supports a fixed header row', async ({ page }) => {
  await signInForTest(page)
  await page.getByRole('button', { name: 'Create new' }).click()
  await page.getByRole('menuitem', { name: 'New document' }).click()

  const editor = page.getByRole('textbox', { name: 'Document content' })
  await editor.click()
  await page.getByRole('button', { name: 'Basic Table' }).click()
  const table = page.locator('.tiptap table')
  await expect(table).toBeVisible()

  const rowGrip = page.getByRole('button', { name: 'Row 1 actions' })
  await rowGrip.click()
  await page.getByRole('menuitemcheckbox', { name: 'Header row' }).click()
  await expect(table.locator('th')).toHaveCount(2)

  await rowGrip.evaluate((button) => (button as HTMLButtonElement).click())
  await page.getByRole('menuitemcheckbox', { name: 'Fixed visible rows' }).click()
  await expect(page.getByRole('spinbutton', { name: 'Visible row count' })).toHaveValue('5')
  await expect(page.getByRole('menuitemcheckbox', { name: 'Fixed header' })).toHaveCount(0)
  const tableWrapper = table.locator('xpath=..')
  await expect(tableWrapper).toHaveAttribute('data-fixed-rows', 'true')
  await expect(table.locator('th').first()).toHaveCSS('position', 'sticky')
})

test('double-clicking text inside a table cell selects text', async ({ page }) => {
  await signInForTest(page)
  await page.getByRole('button', { name: 'Create new' }).click()
  await page.getByRole('menuitem', { name: 'New document' }).click()

  const editor = page.getByRole('textbox', { name: 'Document content' })
  await editor.click()
  await page.getByRole('button', { name: 'Basic Table' }).click()
  const cell = page.locator('.tiptap table td').first()
  await cell.click()
  await page.keyboard.type('selectable text')
  await cell.dblclick({ position: { x: 28, y: 18 } })

  const selectedText = await page.evaluate(() => window.getSelection()?.toString() ?? '')
  expect(selectedText.length).toBeGreaterThan(0)
})

test('table row menu opens above a grip near the viewport bottom', async ({ page }) => {
  await page.setViewportSize({ width: 900, height: 400 })
  await signInForTest(page)
  await page.getByRole('button', { name: 'Create new' }).click()
  await page.getByRole('menuitem', { name: 'New document' }).click()

  const editor = page.getByRole('textbox', { name: 'Document content' })
  await editor.click()
  await page.getByRole('button', { name: 'Basic Table' }).click()
  const table = page.locator('.tiptap table')
  await expect(table).toBeVisible()
  await table.hover()
  const lastGrip = page.getByRole('button', { name: 'Row 1 actions' })
  await lastGrip.evaluate((button) => (button as HTMLButtonElement).click())
  const menu = page.locator('.mybook-table-manual-menu')
  await expect(menu).toBeVisible()
  const gripBox = await lastGrip.boundingBox()
  const menuBox = await menu.boundingBox()
  if (!gripBox || !menuBox) throw new Error('Table grip or menu has no layout box')
  expect(menuBox.y).toBeLessThan(gripBox.y)

  await page.keyboard.press('Escape')
  const columnGrip = page.getByRole('button', { name: 'Column 1 actions' })
  await columnGrip.evaluate((button) => (button as HTMLButtonElement).click())
  await expect(menu).toBeVisible()
  const columnGripBox = await columnGrip.boundingBox()
  const columnMenuBox = await menu.boundingBox()
  if (!columnGripBox || !columnMenuBox) throw new Error('Column grip or menu has no layout box')
  expect(columnMenuBox.y).toBeLessThan(columnGripBox.y)
})

test('document table column grip reorders a picked-up column', async ({ page }) => {
  await signInForTest(page)
  await page.getByRole('button', { name: 'Create new' }).click()
  await page.getByRole('menuitem', { name: 'New document' }).click()

  const editor = page.getByRole('textbox', { name: 'Document content' })
  await editor.click()
  await page.getByRole('button', { name: 'Basic Table' }).click()
  const table = page.locator('.tiptap table')
  await expect(table).toBeVisible()

  await table.locator('td').nth(0).click()
  await page.keyboard.type('A')
  await table.locator('td').nth(1).click()
  await page.keyboard.type('B')

  const firstGrip = page.getByRole('button', { name: 'Column 1 actions' })
  const secondGrip = page.getByRole('button', { name: 'Column 2 actions' })
  const firstGripBox = await firstGrip.boundingBox()
  const secondGripBox = await secondGrip.boundingBox()
  if (!firstGripBox || !secondGripBox) throw new Error('Column grips have no layout boxes')
  await page.mouse.move(firstGripBox.x + firstGripBox.width / 2, firstGripBox.y + firstGripBox.height / 2)
  await page.mouse.down()
  await page.mouse.move(secondGripBox.x + secondGripBox.width / 2 + 12, secondGripBox.y + secondGripBox.height / 2, { steps: 5 })
  await expect(table.locator('.mybook-table-dragging-column')).toHaveCount(2)
  await expect(page.locator('.mybook-table-drag-ghost-column')).toBeVisible()
  await expect(firstGrip).toHaveClass(/is-dragging/)
  await page.mouse.up()

  await expect(table.locator('td').nth(0)).toContainText('B')
  await expect(table.locator('td').nth(1)).toContainText('A')
})

test('document table keyboard navigation keeps focus inside the table', async ({ page }) => {
  await signInForTest(page)
  await page.getByRole('button', { name: 'Create new' }).click()
  await page.getByRole('menuitem', { name: 'New document' }).click()

  const editor = page.getByRole('textbox', { name: 'Document content' })
  await editor.click()
  await page.getByRole('button', { name: 'Basic Table' }).click()
  const table = page.locator('.tiptap table')
  await expect(table).toBeVisible()
  const firstCell = table.locator('td').nth(0)
  const secondCell = table.locator('td').nth(1)
  await firstCell.click()
  await page.keyboard.type('A')
  await page.keyboard.press('ArrowRight')

  const arrowRightCell = await page.evaluate(() => window.getSelection()?.anchorNode?.parentElement?.closest('td')?.cellIndex ?? -1)
  expect(arrowRightCell).toBe(1)

  await page.keyboard.press('Meta+Shift+ArrowLeft')
  const modifiedArrowCell = await page.evaluate(() => window.getSelection()?.anchorNode?.parentElement?.closest('td')?.cellIndex ?? -1)
  expect(modifiedArrowCell).toBe(1)
  await expect(secondCell).toHaveClass(/mybook-active-table-cell/)
})

test('document table grips and menus are keyboard accessible', async ({ page }) => {
  await signInForTest(page)
  await page.getByRole('button', { name: 'Create new' }).click()
  await page.getByRole('menuitem', { name: 'New document' }).click()

  const editor = page.getByRole('textbox', { name: 'Document content' })
  await editor.click()
  await page.getByRole('button', { name: 'Basic Table' }).click()
  const table = page.locator('.tiptap table')
  await expect(table).toBeVisible()

  await table.locator('td').first().click()
  await page.keyboard.press('Tab')
  await expect(table.locator('td').nth(1)).toHaveClass(/mybook-active-table-cell/)
  await page.keyboard.press('Shift+Tab')
  await expect(table.locator('td').first()).toHaveClass(/mybook-active-table-cell/)

  const rowGrip = page.getByRole('button', { name: 'Row 1 actions' })
  await rowGrip.focus()
  await page.keyboard.press('Enter')
  await expect(page.locator('.mybook-table-manual-menu')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.locator('.mybook-table-manual-menu')).toBeHidden()

  await rowGrip.focus()
  await page.keyboard.press('Space')
  await page.getByRole('menuitemcheckbox', { name: 'Header row' }).press('Enter')
  await expect(table.locator('th')).toHaveCount(2)
})
